spring:
  application:
    name: comgithubsince1986demoprofile
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
    producer:
      acks: all #所有kafka节点全接受到才表示发送成功

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

app:
  defaultCharacterEncoding: utf-8

  cors:
    mapping: /**
    allowedOrigins:
      - http://localhost:63342
      - http://localhost:63343
      - http://localhost:63344
    allowedMethods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowedHeaders:
      - Authorization
      - Cache-Control
      - Content-Type
    allowCredentials: true
logging:
  level:
    com.github.since1986.demo.profile.mapper.ProfileMapper: TRACE
    com.github.since1986.demo.profile.mapper.RemoteCallEventMapper: TRACE
---
spring:
  profiles: production
  application:
    name: comgithubsince1986demoprofile
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
    producer:
      acks: all #所有kafka节点全接受到才表示发送成功

server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

app:
  defaultCharacterEncoding: utf-8

  cors:
    mapping: /**
    allowedOrigins:
      - http://localhost:63342
      - http://localhost:63343
      - http://localhost:63344
    allowedMethods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowedHeaders:
      - Authorization
      - Cache-Control
      - Content-Type
    allowCredentials: true
logging:
  level:
    com.github.since1986.demo.profile.mapper.ProfileMapper: ERROR
    com.github.since1986.demo.profile.mapper.RemoteCallEventMapper: ERROR


#高可用配置（三节点）
---
spring:
  profiles: profile1
  application:
    name: comgithubsince1986demoprofile
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
    producer:
      acks: all #所有kafka节点全接受到才表示发送成功

server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/

app:
  defaultCharacterEncoding: utf-8

  cors:
    mapping: /**
    allowedOrigins:
      - http://localhost:63342
      - http://localhost:63343
      - http://localhost:63344
    allowedMethods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowedHeaders:
      - Authorization
      - Cache-Control
      - Content-Type
    allowCredentials: true
logging:
  level:
    com.github.since1986.demo.profile.mapper.ProfileMapper: ERROR
    com.github.since1986.demo.profile.mapper.RemoteCallEventMapper: ERROR

---
spring:
  profiles: profile2
  application:
    name: comgithubsince1986demoprofile
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
    producer:
      acks: all #所有kafka节点全接受到才表示发送成功

server:
  port: 10002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/

app:
  defaultCharacterEncoding: utf-8

  cors:
    mapping: /**
    allowedOrigins:
      - http://localhost:63342
      - http://localhost:63343
      - http://localhost:63344
    allowedMethods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowedHeaders:
      - Authorization
      - Cache-Control
      - Content-Type
    allowCredentials: true
logging:
  level:
    com.github.since1986.demo.profile.mapper.ProfileMapper: ERROR
    com.github.since1986.demo.profile.mapper.RemoteCallEventMapper: ERROR

---
spring:
  profiles: profile3
  application:
    name: comgithubsince1986demoprofile
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
    producer:
      acks: all #所有kafka节点全接受到才表示发送成功

server:
  port: 10003

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/

app:
  defaultCharacterEncoding: utf-8

  cors:
    mapping: /**
    allowedOrigins:
      - http://localhost:63342
      - http://localhost:63343
      - http://localhost:63344
    allowedMethods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    allowedHeaders:
      - Authorization
      - Cache-Control
      - Content-Type
    allowCredentials: true
logging:
  level:
    com.github.since1986.demo.profile.mapper.ProfileMapper: ERROR
    com.github.since1986.demo.profile.mapper.RemoteCallEventMapper: ERROR